// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/ericblois/Development/React_Native/dropthread-app/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/ericblois/Development/React_Native/dropthread-app/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('dropthread', appParameters);
});
require('/Users/ericblois/Development/React_Native/dropthread-app/index.js');